package com.ckun.reminder;

import android.content.*;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import org.json.*;
import java.io.*;
import java.net.*;
import java.nio.charset.StandardCharsets;
import java.util.*;
import java.util.concurrent.Executors;

public final class SyncEngine {
    public interface Callback { void complete(Result result); }
    public static final class Result { public final boolean success;public final String message;public final int uploaded,downloaded,conflicts;Result(boolean ok,String message,int up,int down,int conflicts){success=ok;this.message=message;uploaded=up;downloaded=down;this.conflicts=conflicts;} }
    private static final class Entity {final String type,remote;final android.database.sqlite.SQLiteOpenHelper store;Entity(String type,String remote,android.database.sqlite.SQLiteOpenHelper store){this.type=type;this.remote=remote;this.store=store;}}
    private final Context context;private final AccountSession session;private final String base,key;
    public SyncEngine(Context context){this.context=context.getApplicationContext();session=AccountSession.open(context);base=BuildConfig.SUPABASE_URL.replaceAll("/+$","");key=BuildConfig.SUPABASE_ANON_KEY;}
    public void sync(Callback callback){Executors.newSingleThreadExecutor().execute(()->{Result result;try{if(!session.isSignedIn())throw new IllegalStateException("请先登录账户");if(base.isEmpty()||key.isEmpty())throw new IllegalStateException("尚未配置云端同步服务");android.content.SharedPreferences state=context.getSharedPreferences("sync_state",0);String bound=state.getString("bound_account","");if(!bound.isEmpty()&&!bound.equalsIgnoreCase(session.email()))throw new IllegalStateException("本机数据已绑定其他账户，不能直接切换上传");int first=pullAll(),down=first>>>16,conflicts=first&0xffff;int up=uploadAll();int second=pullAll();down+=second>>>16;conflicts+=second&0xffff;long now=System.currentTimeMillis();state.edit().putString("bound_account",session.email()).putLong("last_success",now).putString("last_error","").apply();result=new Result(true,"同步完成：上传 "+up+"，下载 "+down+(conflicts>0?"，合并冲突 "+conflicts:""),up,down,conflicts);}catch(Exception e){String message=e.getMessage()==null?"同步失败":e.getMessage();context.getSharedPreferences("sync_state",0).edit().putString("last_error",message).apply();result=new Result(false,message,0,0,0);}callback.complete(result);});}
    private List<Entity> entities(){return List.of(new Entity("task","tasks",new TaskStore(context)),new Entity("goal","goals",new GoalStore(context)),new Entity("course","courses",new CourseStore(context)));}
    private Entity entity(String type){if(type.equals("task"))return new Entity(type,"tasks",new TaskStore(context));if(type.equals("goal"))return new Entity(type,"goals",new GoalStore(context));if(type.equals("course"))return new Entity(type,"courses",new CourseStore(context));throw new IllegalArgumentException("Unknown sync entity");}
    private int uploadAll()throws Exception{int count=0;for(Entity entity:entities()){try(entity.store){SQLiteDatabase db=entity.store.getWritableDatabase();try(Cursor c=db.query(entity.remote,null,"sync_dirty=1",null,null,null,"id")){while(c.moveToNext()){JSONObject body=toCloud(entity.type,c);long version=c.getLong(c.getColumnIndexOrThrow("sync_version"));String id=c.getString(c.getColumnIndexOrThrow("sync_id"));String path="/rest/v1/"+entity.remote+(version==0?"?select=*":"?id=eq."+enc(id)+"&sync_version=eq."+version+"&select=*");JSONArray returned=request(version==0?"POST":"PATCH",path,body);if(returned.length()==0)continue;JSONObject saved=returned.getJSONObject(0);ContentValues values=new ContentValues();values.put("sync_version",saved.getLong("sync_version"));values.put("sync_dirty",0);db.update(entity.remote,values,"sync_id=?",new String[]{id});count++;}}}}return count;}
    private int pullAll()throws Exception{long cursor=context.getSharedPreferences("sync_state",0).getLong("cursor",0);int downloaded=0,conflicts=0;while(true){JSONObject body=new JSONObject();body.put("p_after",cursor);body.put("p_limit",500);JSONArray changes=request("POST","/rest/v1/rpc/pull_changes",body);if(changes.length()==0)break;for(int i=0;i<changes.length();i++){JSONObject change=changes.getJSONObject(i),record=change.getJSONObject("payload");Entity entity=entity(change.getString("entity_type"));try(entity.store){SQLiteDatabase db=entity.store.getWritableDatabase();String id=record.getString("id");try(Cursor local=db.query(entity.remote,new String[]{"sync_dirty","sync_version"},"sync_id=?",new String[]{id},null,null,null)){if(local.moveToFirst()&&local.getInt(0)!=0&&local.getLong(1)<record.getLong("sync_version")){ContentValues rebase=new ContentValues();rebase.put("sync_version",record.getLong("sync_version"));db.update(entity.remote,rebase,"sync_id=?",new String[]{id});conflicts++;}else{applyRemote(db,entity.type,entity.remote,record);downloaded++;}}}cursor=change.getLong("sync_seq");}context.getSharedPreferences("sync_state",0).edit().putLong("cursor",cursor).commit();if(changes.length()<500)break;}return(downloaded<<16)|(conflicts&0xffff);}
    private JSONObject toCloud(String type,Cursor c)throws Exception{JSONObject o=new JSONObject();o.put("id",s(c,"sync_id"));o.put("created_at",l(c,"created_at"));o.put("updated_at",l(c,"updated_at"));putNullable(o,"deleted_at",l(c,"deleted_at"));if(type.equals("task")){o.put("title",s(c,"title"));o.put("note",s(c,"note"));o.put("start_at",l(c,"start"));o.put("duration_minutes",i(c,"duration"));o.put("priority",i(c,"priority"));o.put("done",i(c,"done")!=0);putNullable(o,"completed_at",l(c,"completed_at"));JSONArray reminders=new JSONArray();String offsets=s(c,"reminder_offsets");if(!offsets.isEmpty())for(String value:offsets.split(","))reminders.put(Integer.parseInt(value));o.put("reminder_minutes",reminders);}else if(type.equals("goal")){o.put("title",s(c,"title"));o.put("daily_title",s(c,"daily_title"));o.put("deadline",l(c,"deadline"));o.put("daily_hour",i(c,"hour"));o.put("daily_minute",i(c,"minute"));o.put("auto_add",i(c,"auto_add")!=0);}else{o.put("name",s(c,"name"));o.put("location",s(c,"location"));o.put("teacher",s(c,"teacher"));o.put("note",s(c,"note"));o.put("weekday",i(c,"weekday"));o.put("start_period",i(c,"start_period"));o.put("end_period",i(c,"end_period"));o.put("start_week",i(c,"start_week"));o.put("end_week",i(c,"end_week"));o.put("color_index",i(c,"color_index"));}return o;}
    private void applyRemote(SQLiteDatabase db,String type,String table,JSONObject o)throws Exception{ContentValues v=new ContentValues();v.put("sync_id",o.getString("id"));v.put("created_at",o.getLong("created_at"));v.put("updated_at",o.getLong("updated_at"));v.put("deleted_at",nullableLong(o,"deleted_at"));v.put("sync_version",o.getLong("sync_version"));v.put("sync_dirty",0);if(type.equals("task")){v.put("title",o.getString("title"));v.put("note",o.optString("note"));v.put("start",o.getLong("start_at"));v.put("duration",o.getInt("duration_minutes"));v.put("priority",o.getInt("priority"));v.put("done",o.getBoolean("done")?1:0);v.put("completed_at",nullableLong(o,"completed_at"));JSONArray a=o.optJSONArray("reminder_minutes");StringJoiner join=new StringJoiner(",");if(a!=null)for(int i=0;i<a.length();i++)join.add(String.valueOf(a.getInt(i)));v.put("reminder_offsets",join.toString());v.put("ten",a!=null&&contains(a,10)?1:0);v.put("day",a!=null&&contains(a,1440)?1:0);v.put("revision",0);v.put("source_goal_id",0);v.put("source_course_id",0);v.put("generated_day",0);}else if(type.equals("goal")){v.put("title",o.getString("title"));v.put("daily_title",o.optString("daily_title"));v.put("deadline",o.getLong("deadline"));v.put("hour",o.getInt("daily_hour"));v.put("minute",o.getInt("daily_minute"));v.put("auto_add",o.getBoolean("auto_add")?1:0);}else{for(String key:new String[]{"name","location","teacher","note"})v.put(key,o.optString(key));for(String key:new String[]{"weekday","start_period","end_period","start_week","end_week","color_index"})v.put(key,o.getInt(key));}int changed=db.update(table,v,"sync_id=?",new String[]{o.getString("id")});if(changed==0)db.insertOrThrow(table,null,v);}
    private JSONArray request(String method,String path,JSONObject body)throws Exception{HttpURLConnection c=(HttpURLConnection)new URL(base+path).openConnection();try{c.setRequestMethod(method);c.setConnectTimeout(15000);c.setReadTimeout(15000);c.setDoOutput(true);c.setRequestProperty("apikey",key);c.setRequestProperty("Authorization","Bearer "+session.accessToken());c.setRequestProperty("Content-Type","application/json");c.setRequestProperty("Prefer","return=representation");try(OutputStream out=c.getOutputStream()){out.write(body.toString().getBytes(StandardCharsets.UTF_8));}int code=c.getResponseCode();String text=read(code>=200&&code<300?c.getInputStream():c.getErrorStream());if(code==401)throw new IllegalStateException("登录状态已过期，请退出后重新登录");if(code<200||code>=300)throw new IllegalStateException("云端同步失败（"+code+"）");return text.isEmpty()?new JSONArray():new JSONArray(text);}finally{c.disconnect();}}
    private static String read(InputStream in)throws IOException{if(in==null)return"";try(BufferedReader r=new BufferedReader(new InputStreamReader(in,StandardCharsets.UTF_8))){StringBuilder b=new StringBuilder();String line;while((line=r.readLine())!=null)b.append(line);return b.toString();}}
    private static String enc(String s)throws Exception{return URLEncoder.encode(s,StandardCharsets.UTF_8.name());}private static String s(Cursor c,String n){String x=c.getString(c.getColumnIndexOrThrow(n));return x==null?"":x;}private static long l(Cursor c,String n){return c.getLong(c.getColumnIndexOrThrow(n));}private static int i(Cursor c,String n){return c.getInt(c.getColumnIndexOrThrow(n));}private static void putNullable(JSONObject o,String k,long v)throws Exception{o.put(k,v==0?JSONObject.NULL:v);}private static long nullableLong(JSONObject o,String k){return o.isNull(k)?0:o.optLong(k);}private static boolean contains(JSONArray a,int n)throws Exception{for(int i=0;i<a.length();i++)if(a.getInt(i)==n)return true;return false;}
}
