package com.ckun.reminder;

import android.content.Context;
import android.graphics.*;
import android.graphics.drawable.ColorDrawable;
import android.view.*;
import java.time.*;
import java.time.format.DateTimeFormatter;
import java.util.*;

public final class TimetableGridView extends View {
    public interface Listener { void onCourse(Course course); void onEmpty(int weekday, int period); }
    private static final int INK=0xff4A3E35, MUTED=0xff8E7D70, GREEN=0xff52694D, LINE=0xffE8DED1, CREAM=0xffFBF4E9;
    private static final int[] COLORS={0xffAFC4A6,0xffE7ADA5,0xffEBC98F,0xffA9C0DC,0xffC8B8D5,0xffA8D1CB,0xffD7B99C,0xffBBC49D};
    private static final String[] DAYS={"一","二","三","四","五","六","日"};
    private final Paint paint=new Paint(Paint.ANTI_ALIAS_FLAG); private final List<Hit> hits=new ArrayList<>();
    private final float density; private final int gutter, column, header, row, gap; private List<Course> courses=List.of(); private Map<Long,Integer> homework=Map.of(); private int week=1; private Listener listener;
    private static final class Hit { final RectF rect; final Course course; Hit(RectF r,Course c){rect=r;course=c;} }
    public TimetableGridView(Context context){super(context);density=getResources().getDisplayMetrics().density;gutter=dp(58);column=dp(94);header=dp(64);row=dp(66);gap=dp(3);setBackground(new ColorDrawable(Color.TRANSPARENT));setClickable(true);setContentDescription("每周课程表网格");}
    public void setData(List<Course> values,int selectedWeek,Listener value){courses=new ArrayList<>(values);week=selectedWeek;listener=value;invalidate();}
    public void setHomework(Map<Long,Integer> values){homework=new HashMap<>(values);invalidate();}
    private int dp(int n){return Math.round(n*density);}
    @Override protected void onMeasure(int widthSpec,int heightSpec){setMeasuredDimension(gutter+column*7,header+row*13);}
    @Override protected void onDraw(Canvas canvas){super.onDraw(canvas);hits.clear();drawBackground(canvas);drawHeaders(canvas);drawCourses(canvas);}
    private void drawBackground(Canvas c){paint.setStyle(Paint.Style.FILL);paint.setColor(CREAM);c.drawRoundRect(new RectF(0,0,getWidth(),getHeight()),dp(18),dp(18),paint);LocalDate today=LocalDate.now();int current=CourseRules.weekOf(today);if(current==week){int day=today.getDayOfWeek().getValue();paint.setColor(0x197C9270);c.drawRect(gutter+(day-1)*column,0,gutter+day*column,getHeight(),paint);}paint.setStyle(Paint.Style.STROKE);paint.setStrokeWidth(dp(1));paint.setColor(LINE);for(int i=0;i<=7;i++){float x=gutter+i*column;c.drawLine(x,header,x,getHeight(),paint);}for(int i=0;i<=13;i++){float y=header+i*row;c.drawLine(gutter,y,getWidth(),y,paint);}paint.setStyle(Paint.Style.FILL);}
    private void drawHeaders(Canvas c){LocalDate monday=CourseRules.weekMonday(week);for(int day=0;day<7;day++){float center=gutter+day*column+column/2f;LocalDate date=monday.plusDays(day);boolean today=date.equals(LocalDate.now());if(today){paint.setColor(GREEN);c.drawRoundRect(new RectF(center-dp(22),dp(8),center+dp(22),header-dp(8)),dp(16),dp(16),paint);}drawCentered(c,"周"+DAYS[day],center,dp(26),dp(14),today?Color.WHITE:INK,true);drawCentered(c,String.valueOf(date.getDayOfMonth()),center,dp(48),dp(13),today?Color.WHITE:MUTED,false);}for(int i=0;i<13;i++){float top=header+i*row;drawCentered(c,String.valueOf(i+1),gutter/2f,top+dp(23),dp(16),INK,true);String start=CourseRules.PERIOD_STARTS[i].format(DateTimeFormatter.ofPattern("HH:mm"));String end=CourseRules.PERIOD_STARTS[i].plusMinutes(45).format(DateTimeFormatter.ofPattern("HH:mm"));drawCentered(c,start,gutter/2f,top+dp(42),dp(10),MUTED,false);drawCentered(c,end,gutter/2f,top+dp(56),dp(10),MUTED,false);}}
    private void drawCourses(Canvas c){for(Course course:courses){if(week<course.startWeek||week>course.endWeek)continue;List<Course> overlaps=overlaps(course);int index=0;for(int i=0;i<overlaps.size();i++)if(overlaps.get(i).id==course.id)index=i;float available=column-gap*2;float width=available/overlaps.size();float left=gutter+(course.weekday-1)*column+gap+index*width;float right=left+width-gap;float top=header+(course.startPeriod-1)*row+gap;float bottom=header+course.endPeriod*row-gap;RectF rect=new RectF(left,top,right,bottom);paint.setColor(COLORS[Math.floorMod(course.colorIndex,COLORS.length)]);c.drawRoundRect(rect,dp(10),dp(10),paint);paint.setStyle(Paint.Style.STROKE);paint.setStrokeWidth(dp(1));paint.setColor(0x66FFFFFF);c.drawRoundRect(new RectF(left+dp(1),top+dp(1),right-dp(1),bottom-dp(1)),dp(9),dp(9),paint);paint.setStyle(Paint.Style.FILL);hits.add(new Hit(rect,course));c.save();c.clipRect(left+dp(7),top+dp(5),right-dp(5),bottom-dp(4));float y=top+dp(20);y=drawWrapped(c,course.name,left+dp(7),y,right-left-dp(12),dp(14),INK,true,2);if(!course.location.isEmpty())y=drawWrapped(c,"@"+course.location,left+dp(7),y+dp(3),right-left-dp(12),dp(11),INK,false,2);if(bottom-y>dp(18))drawWrapped(c,"第"+course.startWeek+"–"+course.endWeek+"周",left+dp(7),bottom-dp(8),right-left-dp(12),dp(10),0xff6E6258,false,1);c.restore();int count=homework.getOrDefault(course.id,0);if(count>0){float cx=right-dp(8),cy=top+dp(8);paint.setColor(GREEN);c.drawCircle(cx,cy,dp(9),paint);drawCentered(c,count>9?"9+":String.valueOf(count),cx,cy+dp(4),dp(9),Color.WHITE,true);}}}
    private List<Course> overlaps(Course target){List<Course> result=new ArrayList<>();for(Course c:courses)if(c.weekday==target.weekday&&week>=c.startWeek&&week<=c.endWeek&&c.startPeriod<=target.endPeriod&&target.startPeriod<=c.endPeriod)result.add(c);result.sort(Comparator.comparingInt((Course c)->c.startPeriod).thenComparingLong(c->c.id));return result;}
    private float drawWrapped(Canvas c,String value,float x,float baseline,float maxWidth,float size,int color,boolean bold,int maxLines){paint.setTextSize(size);paint.setColor(color);paint.setTypeface(Typeface.create("serif",bold?Typeface.BOLD:Typeface.NORMAL));String remaining=value;float line=baseline;for(int n=0;n<maxLines&&!remaining.isEmpty();n++){int count=paint.breakText(remaining,true,maxWidth,null);if(count<=0)break;String part=remaining.substring(0,count);if(n==maxLines-1&&count<remaining.length()&&count>1)part=part.substring(0,count-1)+"…";c.drawText(part,x,line,paint);remaining=remaining.substring(count);line+=size+dp(3);}return line;}
    private void drawCentered(Canvas c,String value,float x,float baseline,float size,int color,boolean bold){paint.setTextSize(size);paint.setColor(color);paint.setTypeface(Typeface.create("serif",bold?Typeface.BOLD:Typeface.NORMAL));paint.setTextAlign(Paint.Align.CENTER);c.drawText(value,x,baseline,paint);paint.setTextAlign(Paint.Align.LEFT);}
    @Override public boolean onTouchEvent(android.view.MotionEvent event){if(event.getAction()!=MotionEvent.ACTION_UP)return true;for(Hit hit:hits)if(hit.rect.contains(event.getX(),event.getY())){if(listener!=null)listener.onCourse(hit.course);performClick();return true;}if(event.getX()>=gutter&&event.getY()>=header){int day=Math.min(7,Math.max(1,(int)((event.getX()-gutter)/column)+1));int period=Math.min(13,Math.max(1,(int)((event.getY()-header)/row)+1));if(listener!=null)listener.onEmpty(day,period);performClick();}return true;}
    @Override public boolean performClick(){super.performClick();return true;}
}
