package com.ckun.reminder;

import android.app.*;
import android.content.Intent;
import android.graphics.*;
import android.graphics.drawable.GradientDrawable;
import android.os.Bundle;
import android.text.InputType;
import android.view.*;
import android.widget.*;
import java.time.*;
import java.time.format.DateTimeFormatter;
import java.util.*;

public final class TimetableActivity extends Activity {
    private static final int BG=0xffFFF8ED, INK=0xff4A3E35, MUTED=0xff8E7D70, GREEN=0xff7C9270, CREAM=0xffF5EBDD, CARD=0xffFFFCF7;
    private static final int[] COLORS={0xff7C9270,0xffB98474,0xffC39A58,0xff728CA5,0xff927CA0,0xff72A09A,0xffA68468,0xff89916B};
    private static final String[] DAYS={"周一","周二","周三","周四","周五","周六","周日"};
    private LinearLayout page; private int week; private int mode; private CourseStore courses;
    private int dp(int n){return Math.round(n*getResources().getDisplayMetrics().density);}
    private GradientDrawable shape(int color,int radius){GradientDrawable d=new GradientDrawable();d.setColor(color);d.setCornerRadius(dp(radius));return d;}
    private TextView text(String s,int size,int color){TextView v=new TextView(this);v.setText(s);v.setTextSize(size);v.setTextColor(color);v.setTypeface(Typeface.create("serif",Typeface.NORMAL));v.setPadding(0,dp(4),0,dp(4));return v;}
    private Button button(String s,boolean primary,View.OnClickListener l){Button b=new Button(this);b.setText(s);b.setAllCaps(false);b.setTextSize(14);b.setTypeface(Typeface.create("serif",Typeface.NORMAL));b.setTextColor(primary?Color.WHITE:GREEN);b.setBackground(shape(primary?GREEN:CREAM,20));b.setOnClickListener(l);return b;}
    @Override public void onCreate(Bundle state){super.onCreate(state);courses=new CourseStore(this);week=Math.max(1,Math.min(16,CourseRules.weekOf(LocalDate.now())));if(state!=null){week=state.getInt("week",week);mode=state.getInt("mode");}show();}
    @Override protected void onSaveInstanceState(Bundle out){super.onSaveInstanceState(out);out.putInt("week",week);out.putInt("mode",mode);}
    @Override protected void onDestroy(){courses.close();super.onDestroy();}
    private void shell(){ScrollView scroll=new ScrollView(this);scroll.setFillViewport(true);scroll.setBackgroundColor(BG);page=new LinearLayout(this);page.setOrientation(LinearLayout.VERTICAL);page.setPadding(dp(20),dp(8),dp(20),dp(36));scroll.addView(page);setContentView(scroll);scroll.setOnApplyWindowInsetsListener((v,i)->{v.setPadding(i.getSystemWindowInsetLeft(),i.getSystemWindowInsetTop()+dp(8),i.getSystemWindowInsetRight(),i.getSystemWindowInsetBottom());return i;});}
    private void show(){shell(); LinearLayout top=new LinearLayout(this);top.setGravity(Gravity.CENTER_VERTICAL);top.addView(button("‹  返回",false,v->finish()),new LinearLayout.LayoutParams(-2,dp(42)));TextView title=text("课程表",29,INK);title.setTypeface(Typeface.DEFAULT_BOLD);LinearLayout.LayoutParams tp=new LinearLayout.LayoutParams(0,-2,1);tp.leftMargin=dp(12);top.addView(title,tp);page.addView(top);
        page.addView(text("2026 秋季学期 · 9月7日起 · 共16周",14,MUTED));gap(14);
        LinearLayout modes=new LinearLayout(this);String[] names={"查看","编辑","作业"};for(int i=0;i<3;i++){final int m=i;Button b=button(names[i],mode==i,v->{mode=m;show();});LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(0,dp(46),1);if(i>0)p.leftMargin=dp(8);modes.addView(b,p);}page.addView(modes);gap(12);
        LinearLayout nav=new LinearLayout(this);nav.setGravity(Gravity.CENTER);Button prev=button("‹",false,v->{if(week>1){week--;show();}});Button next=button("›",false,v->{if(week<16){week++;show();}});TextView label=text("第 "+week+" 周\n"+CourseRules.weekMonday(week).format(DateTimeFormatter.ofPattern("M月d日"))+"—"+CourseRules.weekMonday(week).plusDays(6).format(DateTimeFormatter.ofPattern("M月d日")),18,INK);label.setGravity(Gravity.CENTER);label.setTypeface(Typeface.DEFAULT_BOLD);nav.addView(prev,new LinearLayout.LayoutParams(dp(58),dp(50)));nav.addView(label,new LinearLayout.LayoutParams(0,-2,1));nav.addView(next,new LinearLayout.LayoutParams(dp(58),dp(50)));page.addView(nav);gap(10);
        List<Course> all=courses.all();for(int day=1;day<=7;day++)addDay(day,all);
        if(mode==1){gap(12);Button add=button("＋ 添加课程",true,v->editCourse(new Course()));add.setTag("add-course");page.addView(add,new LinearLayout.LayoutParams(-1,dp(52)));}
    }
    private void addDay(int day,List<Course> all){TextView h=text(DAYS[day-1],17,GREEN);h.setTypeface(Typeface.DEFAULT_BOLD);LinearLayout.LayoutParams hp=new LinearLayout.LayoutParams(-1,-2);hp.topMargin=dp(10);page.addView(h,hp);boolean any=false;for(Course c:all)if(c.weekday==day&&week>=c.startWeek&&week<=c.endWeek){any=true;LinearLayout card=new LinearLayout(this);card.setOrientation(LinearLayout.VERTICAL);card.setPadding(dp(15),dp(11),dp(15),dp(11));card.setBackground(shape(tint(COLORS[Math.floorMod(c.colorIndex,COLORS.length)]),20));TextView name=text(c.name,18,INK);name.setTypeface(Typeface.DEFAULT_BOLD);card.addView(name);String line=c.startPeriod+"–"+c.endPeriod+"节 · "+timeRange(c)+(c.location.isEmpty()?"":" · "+c.location);card.addView(text(line,14,MUTED));if(mode==2){int count=homeworkCount(c.id);card.addView(text(count==0?"暂无未完成作业":"未完成作业 "+count+" 项",13,count==0?MUTED:COLORS[Math.floorMod(c.colorIndex,COLORS.length)]));}card.setOnClickListener(v->{if(mode==1)editCourse(c);else courseDetails(c);});LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.bottomMargin=dp(8);page.addView(card,p);}if(!any){TextView empty=text(mode==1?"点击下方按钮添加课程":"没有课程",13,MUTED);empty.setPadding(dp(12),dp(6),0,dp(8));page.addView(empty);}}
    private int tint(int color){return Color.rgb((Color.red(color)+255*4)/5,(Color.green(color)+255*4)/5,(Color.blue(color)+255*4)/5);}
    private String timeRange(Course c){return CourseRules.PERIOD_STARTS[c.startPeriod-1]+"–"+CourseRules.PERIOD_STARTS[c.endPeriod-1].plusMinutes(45);}
    private void courseDetails(Course c){StringBuilder msg=new StringBuilder(c.startPeriod+"–"+c.endPeriod+"节 · "+timeRange(c)+"\n第"+c.startWeek+"–"+c.endWeek+"周");if(!c.location.isEmpty())msg.append("\n地点：").append(c.location);if(!c.teacher.isEmpty())msg.append("\n教师：").append(c.teacher);if(!c.note.isEmpty())msg.append("\n").append(c.note);new AlertDialog.Builder(this).setTitle(c.name).setMessage(msg).setNegativeButton("关闭",null).setPositiveButton("添加作业",(d,w)->addHomework(c)).show();}
    private void editCourse(Course source){Course c=copy(source);LinearLayout form=form();EditText name=input("课程名称",c.name);form.addView(name);Spinner day=spinner(DAYS,c.weekday-1);form.addView(labeled("星期",day));Spinner start=numberSpinner(13,c.startPeriod);form.addView(labeled("开始节次",start));Spinner end=numberSpinner(13,c.endPeriod);form.addView(labeled("结束节次",end));Spinner from=numberSpinner(16,c.startWeek);form.addView(labeled("开始周",from));Spinner to=numberSpinner(16,c.endWeek);form.addView(labeled("结束周",to));EditText location=input("地点（选填）",c.location),teacher=input("任课老师（选填）",c.teacher),note=input("备注（选填）",c.note);form.addView(location);form.addView(teacher);form.addView(note);Spinner color=spinner(new String[]{"松绿","陶红","麦黄","雾蓝","灰紫","湖绿","浅棕","苔绿"},c.colorIndex);form.addView(labeled("课程颜色",color));AlertDialog dialog=new AlertDialog.Builder(this).setTitle(c.id==0?"添加课程":"编辑课程").setView(form).setNegativeButton("取消",null).setPositiveButton("保存",null).create();if(c.id!=0)dialog.setButton(AlertDialog.BUTTON_NEUTRAL,"删除",(d,w)->{});dialog.setOnShowListener(x->{dialog.getButton(AlertDialog.BUTTON_POSITIVE).setOnClickListener(v->{c.name=name.getText().toString().trim();c.weekday=day.getSelectedItemPosition()+1;c.startPeriod=start.getSelectedItemPosition()+1;c.endPeriod=end.getSelectedItemPosition()+1;c.startWeek=from.getSelectedItemPosition()+1;c.endWeek=to.getSelectedItemPosition()+1;c.location=location.getText().toString().trim();c.teacher=teacher.getText().toString().trim();c.note=note.getText().toString().trim();c.colorIndex=color.getSelectedItemPosition();String error=CourseRules.validate(c);if(error!=null){Toast.makeText(this,error,Toast.LENGTH_LONG).show();return;}boolean conflict=conflicts(c);courses.save(c);dialog.dismiss();show();Toast.makeText(this,conflict?"课程已保存，但与已有课程时间重叠":"课程已保存",Toast.LENGTH_LONG).show();});if(c.id!=0)dialog.getButton(AlertDialog.BUTTON_NEUTRAL).setOnClickListener(v->new AlertDialog.Builder(this).setTitle("删除这门课程？").setMessage("已经创建的作业会保留在待办中。").setNegativeButton("保留",null).setPositiveButton("删除",(a,b)->{courses.delete(c.id);dialog.dismiss();show();}).show());});dialog.show();}
    private boolean conflicts(Course c){for(Course other:courses.all())if(other.id!=c.id&&other.weekday==c.weekday&&rangesOverlap(c.startPeriod,c.endPeriod,other.startPeriod,other.endPeriod)&&rangesOverlap(c.startWeek,c.endWeek,other.startWeek,other.endWeek))return true;return false;}
    private boolean rangesOverlap(int a,int b,int c,int d){return a<=d&&c<=b;}
    private void addHomework(Course c){LocalDateTime now=LocalDateTime.now();LocalDateTime next=CourseRules.nextOccurrence(c,now);if(next==null){Toast.makeText(this,"本学期已没有下一次课程，无法自动安排提醒",Toast.LENGTH_LONG).show();return;}LinearLayout form=form();EditText title=input("作业内容","");form.addView(title);TextView info=text("下次上课："+next.format(DateTimeFormatter.ofPattern("M月d日 E HH:mm",Locale.CHINA)),13,MUTED);form.addView(info);final LocalDateTime[] deadline={null};Button deadlineButton=button("截止时间（选填）",false,v->{LocalDate initial=next.toLocalDate();new DatePickerDialog(this,(dv,y,m,d)->new TimePickerDialog(this,(tv,h,min)->{deadline[0]=LocalDateTime.of(y,m+1,d,h,min);((Button)v).setText("截止："+deadline[0].format(DateTimeFormatter.ofPattern("M月d日 HH:mm")));},20,0,true).show(),initial.getYear(),initial.getMonthValue()-1,initial.getDayOfMonth()).show();});form.addView(deadlineButton,new LinearLayout.LayoutParams(-1,dp(50)));LocalDateTime automatic=CourseRules.defaultHomeworkReminder(next,now);form.addView(text(automatic==null?"默认提醒时间已过去，创建后请手动添加提醒":"默认提醒："+automatic.format(DateTimeFormatter.ofPattern("M月d日 E HH:mm",Locale.CHINA))+"（填写截止时间后改为截止时提醒）",13,GREEN));new AlertDialog.Builder(this).setTitle(c.name+" · 添加作业").setView(form).setNegativeButton("取消",null).setPositiveButton("创建",(d,w)->createHomework(c,title.getText().toString().trim(),deadline[0],next,automatic)).show();}
    private void createHomework(Course c,String value,LocalDateTime deadline,LocalDateTime next,LocalDateTime automatic){if(value.isEmpty()){Toast.makeText(this,"请填写作业内容",Toast.LENGTH_LONG).show();return;}Task task=new Task();task.title=c.name+"："+value;task.note="课程作业 · "+c.startPeriod+"–"+c.endPeriod+"节"+(c.location.isEmpty()?"":" · "+c.location);task.sourceCourseId=c.id;LocalDateTime anchor=deadline==null?next:deadline;if(!anchor.isAfter(LocalDateTime.now())){Toast.makeText(this,"截止时间需要晚于当前时间",Toast.LENGTH_LONG).show();return;}task.start=millis(anchor);task.priority=2;task.reminderMinutes=new TreeSet<>();if(deadline!=null)task.reminderMinutes.add(0);else if(automatic!=null){long minutes=java.time.Duration.between(automatic,anchor).toMinutes();if(minutes>=0&&minutes<=Integer.MAX_VALUE)task.reminderMinutes.add((int)minutes);}try(TaskStore store=new TaskStore(this)){store.save(task);}new ReminderScheduler(this).schedule(task);show();new AlertDialog.Builder(this).setTitle("作业已加入待办").setMessage("默认提醒已创建。你可以继续增加、修改或删除提醒时间。").setNegativeButton("完成",null).setPositiveButton("编辑提醒",(d,w)->startActivity(new Intent(this,MainActivity.class).putExtra("id",task.id))).show();}
    private long millis(LocalDateTime value){return value.atZone(ZoneId.systemDefault()).toInstant().toEpochMilli();}
    private int homeworkCount(long courseId){int n=0;try(TaskStore store=new TaskStore(this)){for(Task t:store.all())if(t.sourceCourseId==courseId&&!t.done)n++;}return n;}
    private LinearLayout form(){LinearLayout f=new LinearLayout(this);f.setOrientation(LinearLayout.VERTICAL);f.setPadding(dp(18),dp(4),dp(18),0);return f;}
    private EditText input(String hint,String value){EditText e=new EditText(this);e.setHint(hint);e.setText(value);e.setSingleLine(true);e.setTextColor(INK);e.setTextSize(15);e.setPadding(dp(12),dp(10),dp(12),dp(10));e.setBackground(shape(CARD,14));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.bottomMargin=dp(8);e.setLayoutParams(p);return e;}
    private Spinner spinner(String[] values,int selected){Spinner s=new Spinner(this);s.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,values));s.setSelection(Math.max(0,Math.min(values.length-1,selected)));return s;}
    private Spinner numberSpinner(int count,int selected){String[] v=new String[count];for(int i=0;i<count;i++)v[i]="第 "+(i+1)+(count==16?" 周":" 节");return spinner(v,selected-1);}
    private LinearLayout labeled(String label,View view){LinearLayout row=new LinearLayout(this);row.setGravity(Gravity.CENTER_VERTICAL);TextView name=text(label,14,GREEN);row.addView(name,new LinearLayout.LayoutParams(0,-2,1));row.addView(view,new LinearLayout.LayoutParams(dp(170),dp(48)));return row;}
    private Course copy(Course s){Course c=new Course();c.id=s.id;c.name=s.name;c.weekday=s.weekday;c.startPeriod=s.startPeriod;c.endPeriod=s.endPeriod;c.startWeek=s.startWeek;c.endWeek=s.endWeek;c.location=s.location;c.teacher=s.teacher;c.note=s.note;c.colorIndex=s.colorIndex;return c;}
    private void gap(int n){View v=new View(this);page.addView(v,new LinearLayout.LayoutParams(1,dp(n)));}
}
