package com.ckun.reminder;

import android.content.Context;
import android.graphics.*;
import android.view.*;
import java.time.*;
import java.util.*;

/** Compact phone-first timetable: all seven days and thirteen periods fit in one viewport. */
public final class TimetableGridView extends View {
    public interface Listener { void onCourse(Course course); void onEmpty(int weekday,int period); void onNavigate(int direction); }
    private static final int INK=0xff4A3E35,MUTED=0xff8E7D70,GREEN=0xff52694D,LINE=0xffE8DED1,CREAM=0xffFBF4E9;
    private static final int[] COLORS={0xffAFC4A6,0xffE7ADA5,0xffEBC98F,0xffA9C0DC,0xffC8B8D5,0xffA8D1CB,0xffD7B99C,0xffBBC49D};
    private static final String[] DAYS={"一","二","三","四","五","六","日"};
    private final Paint paint=new Paint(Paint.ANTI_ALIAS_FLAG);private final List<Hit> hits=new ArrayList<>();private final float density;
    private List<Course> courses=List.of();private Map<Long,Integer> homework=Map.of();private int week=1;private Listener listener;
    private float gutter,header,column,row,gap,touchDownX,touchDownY;
    private static final class Hit{final RectF rect;final Course course;Hit(RectF r,Course c){rect=r;course=c;}}
    public TimetableGridView(Context context){super(context);density=getResources().getDisplayMetrics().density;setClickable(true);setContentDescription("每周课程表网格");}
    public void setData(List<Course> values,int selectedWeek,Listener value){courses=new ArrayList<>(values);week=selectedWeek;listener=value;invalidate();}
    public void setHomework(Map<Long,Integer> values){homework=new HashMap<>(values);invalidate();}
    private float dp(float n){return n*density;}
    @Override protected void onSizeChanged(int w,int h,int oldw,int oldh){gutter=Math.min(dp(34),w*.1f);header=Math.min(dp(42),h*.075f);column=(w-gutter)/7f;row=(h-header)/13f;gap=Math.max(dp(1),Math.min(dp(2),column*.035f));}
    @Override protected void onDraw(Canvas canvas){super.onDraw(canvas);hits.clear();drawBase(canvas);drawLabels(canvas);drawCourses(canvas);}
    private void drawBase(Canvas c){paint.setStyle(Paint.Style.FILL);paint.setColor(CREAM);c.drawRoundRect(new RectF(0,0,getWidth(),getHeight()),dp(12),dp(12),paint);LocalDate today=LocalDate.now();if(CourseRules.weekOf(today)==week){int day=today.getDayOfWeek().getValue();paint.setColor(0x147C9270);c.drawRect(gutter+(day-1)*column,0,gutter+day*column,getHeight(),paint);}paint.setStyle(Paint.Style.STROKE);paint.setStrokeWidth(Math.max(1,dp(.6f)));paint.setColor(LINE);for(int i=0;i<=7;i++)c.drawLine(gutter+i*column,header,gutter+i*column,getHeight(),paint);for(int i=0;i<=13;i++)c.drawLine(gutter,header+i*row,getWidth(),header+i*row,paint);paint.setStyle(Paint.Style.FILL);}
    private void drawLabels(Canvas c){LocalDate monday=CourseRules.weekMonday(week);for(int d=0;d<7;d++){LocalDate date=monday.plusDays(d);float x=gutter+d*column+column/2f;boolean today=date.equals(LocalDate.now());if(today){paint.setColor(GREEN);c.drawRoundRect(new RectF(x-column*.34f,dp(3),x+column*.34f,header-dp(3)),dp(9),dp(9),paint);}center(c,"周"+DAYS[d],x,header*.43f,Math.min(dp(9),column*.2f),today?Color.WHITE:INK,true);center(c,String.valueOf(date.getDayOfMonth()),x,header*.78f,Math.min(dp(9),column*.2f),today?Color.WHITE:MUTED,false);}for(int p=0;p<13;p++){float y=header+p*row;center(c,String.valueOf(p+1),gutter*.42f,y+row*.43f,Math.min(dp(10),row*.3f),INK,true);center(c,CourseRules.PERIOD_STARTS[p].toString(),gutter*.48f,y+row*.75f,Math.min(dp(6.5f),gutter*.19f),MUTED,false);}}
    private void drawCourses(Canvas c){for(Course course:courses){if(week<course.startWeek||week>course.endWeek)continue;List<Course> group=overlaps(course);int index=0;for(int i=0;i<group.size();i++)if(group.get(i).id==course.id)index=i;float width=(column-gap*2)/group.size();float left=gutter+(course.weekday-1)*column+gap+index*width,right=left+width-gap;float top=header+(course.startPeriod-1)*row+gap,bottom=header+course.endPeriod*row-gap;RectF rect=new RectF(left,top,right,bottom);paint.setColor(COLORS[Math.floorMod(course.colorIndex,COLORS.length)]);c.drawRoundRect(rect,dp(5),dp(5),paint);hits.add(new Hit(rect,course));c.save();c.clipRect(rect);float textWidth=right-left-dp(4);float size=Math.min(dp(9),Math.max(dp(6.2f),column*.19f));float locationSize=Math.max(dp(5.5f),size*.76f);float nameBaseline=top+size+dp(2);float locationBaseline=bottom-dp(3);int nameLines=Math.max(1,(int)((locationBaseline-locationSize*1.25f-nameBaseline)/(size*1.18f))+1);wrapped(c,course.name,left+dp(2),nameBaseline,textWidth,size,INK,true,nameLines);singleLine(c,CourseRules.locationLabel(course),left+dp(2),locationBaseline,textWidth,locationSize,0xff655A51);c.restore();int count=homework.getOrDefault(course.id,0);if(count>0){float radius=Math.min(dp(6.5f),column*.14f),cx=right-radius*.8f,cy=top+radius*.8f;paint.setColor(GREEN);c.drawCircle(cx,cy,radius,paint);center(c,count>9?"9+":String.valueOf(count),cx,cy+radius*.38f,Math.max(dp(5),radius*.9f),Color.WHITE,true);}}}
    private List<Course> overlaps(Course target){List<Course> result=new ArrayList<>();for(Course c:courses)if(c.weekday==target.weekday&&week>=c.startWeek&&week<=c.endWeek&&c.startPeriod<=target.endPeriod&&target.startPeriod<=c.endPeriod)result.add(c);result.sort(Comparator.comparingInt((Course c)->c.startPeriod).thenComparingLong(c->c.id));return result;}
    private void wrapped(Canvas c,String value,float x,float baseline,float maxWidth,float size,int color,boolean bold,int lines){paint.setTextSize(size);paint.setColor(color);paint.setTypeface(Typeface.create("sans-serif",bold?Typeface.BOLD:Typeface.NORMAL));String rest=value;float y=baseline;for(int n=0;n<lines&&!rest.isEmpty();n++){int count=paint.breakText(rest,true,maxWidth,null);if(count<1)return;String part=rest.substring(0,count);if(n==lines-1&&count<rest.length()&&count>1)part=part.substring(0,count-1)+"…";c.drawText(part,x,y,paint);rest=rest.substring(count);y+=size*1.18f;}}
    private void singleLine(Canvas c,String value,float x,float baseline,float maxWidth,float size,int color){paint.setTextSize(size);paint.setColor(color);paint.setTypeface(Typeface.create("sans-serif",Typeface.NORMAL));int count=paint.breakText(value,true,maxWidth,null);String shown=value.substring(0,count);if(count<value.length()&&count>1)shown=shown.substring(0,count-1)+"…";c.drawText(shown,x,baseline,paint);}
    private void center(Canvas c,String value,float x,float baseline,float size,int color,boolean bold){paint.setTextSize(size);paint.setColor(color);paint.setTypeface(Typeface.create("serif",bold?Typeface.BOLD:Typeface.NORMAL));paint.setTextAlign(Paint.Align.CENTER);c.drawText(value,x,baseline,paint);paint.setTextAlign(Paint.Align.LEFT);}
    @Override public boolean onTouchEvent(MotionEvent event){if(event.getAction()==MotionEvent.ACTION_DOWN){touchDownX=event.getX();touchDownY=event.getY();return true;}if(event.getAction()!=MotionEvent.ACTION_UP)return true;float dx=event.getX()-touchDownX,dy=event.getY()-touchDownY;if(Math.abs(dx)>dp(40)&&Math.abs(dx)>Math.abs(dy)){if(listener!=null)listener.onNavigate(dx<0?1:-1);performClick();return true;}for(Hit hit:hits)if(hit.rect.contains(event.getX(),event.getY())){if(listener!=null)listener.onCourse(hit.course);performClick();return true;}if(event.getX()>=gutter&&event.getY()>=header){int day=Math.min(7,Math.max(1,(int)((event.getX()-gutter)/column)+1));int period=Math.min(13,Math.max(1,(int)((event.getY()-header)/row)+1));if(listener!=null)listener.onEmpty(day,period);performClick();}return true;}
    @Override public boolean performClick(){super.performClick();return true;}
}
