using System.Windows;
using System.Windows.Controls;
using System.Windows.Media;

namespace LightTodo.Windows;
public sealed class AccountWindow : Window {
    readonly WindowsAccountSession session=new();readonly IAccountAuth auth=new SupabaseAccountAuth();readonly StackPanel panel=new(){Margin=new(28)};
    public AccountWindow(){Title="账户与同步";Width=470;SizeToContent=SizeToContent.Height;WindowStartupLocation=WindowStartupLocation.CenterOwner;Background=new SolidColorBrush((Color)ColorConverter.ConvertFromString("#F4F1E9"));Content=panel;Render();}
    void Render(){panel.Children.Clear();panel.Children.Add(new TextBlock{Text="账户与同步",FontSize=25,FontWeight=FontWeights.SemiBold,Margin=new(0,0,0,16)});if(session.IsSignedIn){panel.Children.Add(new TextBlock{Text="已登录",Foreground=Brushes.DimGray});panel.Children.Add(new TextBlock{Text=session.Email,FontSize=19,Margin=new(0,5,0,8)});panel.Children.Add(new TextBlock{Text="账户已连接。云端数据同步将在下一阶段启用。",TextWrapping=TextWrapping.Wrap});var logout=new Button{Content="退出登录",Margin=new(0,18,0,0),Padding=new(16,9,16,9)};logout.Click+=(s,e)=>{session.Clear();Render();};panel.Children.Add(logout);return;}var email=EmailInput("邮箱");var password=PasswordInput("密码（至少 8 位，包含字母和数字）");var status=new TextBlock{Foreground=Brushes.DimGray,TextWrapping=TextWrapping.Wrap,Margin=new(0,8,0,8)};panel.Children.Add(email);panel.Children.Add(password);panel.Children.Add(status);var login=Button("登录");var signup=Button("注册");var reset=Button("忘记密码");panel.Children.Add(login);panel.Children.Add(signup);panel.Children.Add(reset);async Task Run(Func<Task<AccountResult>> action){var error=AccountRules.ValidateEmail(email.Text)??AccountRules.ValidatePassword(password.Password);if(error!=null){status.Text=error;return;}login.IsEnabled=signup.IsEnabled=reset.IsEnabled=false;var result=await action();login.IsEnabled=signup.IsEnabled=reset.IsEnabled=true;if(result.Success&&result.AccessToken.Length>0){session.Save(result);Render();}else status.Text=result.Message;}login.Click+=async(s,e)=>await Run(()=>auth.SignIn(email.Text.Trim(),password.Password));signup.Click+=async(s,e)=>await Run(()=>auth.SignUp(email.Text.Trim(),password.Password));reset.Click+=async(s,e)=>{var error=AccountRules.ValidateEmail(email.Text);if(error!=null){status.Text=error;return;}login.IsEnabled=signup.IsEnabled=reset.IsEnabled=false;var result=await auth.ResetPassword(email.Text.Trim());login.IsEnabled=signup.IsEnabled=reset.IsEnabled=true;status.Text=result.Message;};}
    TextBox EmailInput(string hint){var value=new TextBox{Padding=new(10),Margin=new(0,0,0,10)};value.ToolTip=hint;return value;}
    PasswordBox PasswordInput(string hint){var value=new PasswordBox{Padding=new(10),Margin=new(0,0,0,10)};value.ToolTip=hint;return value;}
    Button Button(string text)=>new(){Content=text,Padding=new(16,9,16,9),Margin=new(0,4,0,0)};
}
