using System.Windows;
using System.Windows.Controls;
using System.Windows.Media;
namespace LightTodo.Windows;
public sealed class AccountWindow : Window {
    readonly LocalStore store;readonly WindowsAccountSession session=new();readonly IAccountAuth auth=new SupabaseAccountAuth();readonly StackPanel panel=new(){Margin=new(28)};
    public AccountWindow(LocalStore store){this.store=store;Title="账户与同步";Width=470;SizeToContent=SizeToContent.Height;WindowStartupLocation=WindowStartupLocation.CenterOwner;Background=new SolidColorBrush((Color)ColorConverter.ConvertFromString("#F4F1E9"));Content=panel;Render();}
    void Render(){panel.Children.Clear();panel.Children.Add(new TextBlock{Text="账户与同步",FontSize=25,FontWeight=FontWeights.SemiBold,Margin=new(0,0,0,16)});if(session.IsSignedIn){panel.Children.Add(new TextBlock{Text="已登录",Foreground=Brushes.DimGray});panel.Children.Add(new TextBlock{Text=session.Email,FontSize=19,Margin=new(0,5,0,8)});var status=new TextBlock{Text="本地修改会上传，其他设备的更新会增量下载。",TextWrapping=TextWrapping.Wrap,Margin=new(0,6,0,8)};panel.Children.Add(status);var sync=Button("立即同步");sync.Click+=async(s,e)=>{sync.IsEnabled=false;status.Text="正在同步…";var result=await new WindowsSyncEngine(store).Sync();status.Text=result.Message;sync.IsEnabled=true;};panel.Children.Add(sync);var logout=Button("退出登录");logout.Margin=new(0,18,0,0);logout.Click+=(s,e)=>{session.Clear();Render();};panel.Children.Add(logout);return;}var email=EmailInput("邮箱");var password=PasswordInput("密码（至少 8 位，包含字母和数字）");var message=new TextBlock{Foreground=Brushes.DimGray,TextWrapping=TextWrapping.Wrap,Margin=new(0,8,0,8)};panel.Children.Add(email);panel.Children.Add(password);panel.Children.Add(message);var login=Button("登录");var signup=Button("注册");var reset=Button("忘记密码");panel.Children.Add(login);panel.Children.Add(signup);panel.Children.Add(reset);async Task Run(Func<Task<AccountResult>> action){var error=AccountRules.ValidateEmail(email.Text)??AccountRules.ValidatePassword(password.Password);if(error!=null){message.Text=error;return;}login.IsEnabled=signup.IsEnabled=reset.IsEnabled=false;var result=await action();login.IsEnabled=signup.IsEnabled=reset.IsEnabled=true;if(result.Success&&result.AccessToken.Length>0){session.Save(result);Render();}else message.Text=result.Message;}login.Click+=async(s,e)=>await Run(()=>auth.SignIn(email.Text.Trim(),password.Password));signup.Click+=async(s,e)=>await Run(()=>auth.SignUp(email.Text.Trim(),password.Password));reset.Click+=async(s,e)=>{var error=AccountRules.ValidateEmail(email.Text);if(error!=null){message.Text=error;return;}var result=await auth.ResetPassword(email.Text.Trim());message.Text=result.Message;};}
    TextBox EmailInput(string hint)=>new(){ToolTip=hint,Padding=new(10),Margin=new(0,0,0,10)};
    PasswordBox PasswordInput(string hint)=>new(){ToolTip=hint,Padding=new(10),Margin=new(0,0,0,10)};
    Button Button(string text)=>new(){Content=text,Padding=new(16,9,16,9),Margin=new(0,4,0,0)};
}
