using System.Runtime.InteropServices;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Interop;
using System.Windows.Media;

namespace LightTodo.Windows;
public partial class MainWindow : Window {
    readonly LocalStore store = new(); ReminderService? reminders; string page="today"; DateTime selected=DateTime.Today;
    static readonly string[] priorityNames = ["重要且紧急","不重要但紧急","重要不紧急","不重要不紧急"];
    static readonly Color[] priorityColors = [C("#C75C57"),C("#C28A43"),C("#5D83B8"),C("#6F8B78")];
    public MainWindow() { InitializeComponent(); PageSubtitle.Text=DateTime.Now.ToString("yyyy年M月d日 dddd"); }
    void OnLoaded(object s, RoutedEventArgs e) { ApplyBackdrop(); reminders=new(store); GenerateGoalTasks(); RefreshAccountStatus(); RenderToday(); }
    void OnClosing(object? s, System.ComponentModel.CancelEventArgs e) { reminders?.Dispose(); store.Save(); }
    void ApplyBackdrop() { var h=new WindowInteropHelper(this).Handle; int backdrop=2, dark=0; DwmSetWindowAttribute(h,38,ref backdrop,4); DwmSetWindowAttribute(h,20,ref dark,4); }
    [DllImport("dwmapi.dll")] static extern int DwmSetWindowAttribute(IntPtr hwnd,int attr,ref int value,int size);
    void Account_Click(object sender,RoutedEventArgs e){new AccountWindow{Owner=this}.ShowDialog();RefreshAccountStatus();}
    void RefreshAccountStatus(){var session=new WindowsAccountSession();var signedIn=session.IsSignedIn;AccountButton.Content=signedIn?"管理账户":"登录或注册";StorageTitle.Text=signedIn?session.Email:"本地存储";StorageSubtitle.Text=signedIn?"账户已连接，数据同步将在下一阶段启用":"数据仅保存在这台电脑";}
    static Color C(string s)=>(Color)ColorConverter.ConvertFromString(s);
    Border Card(UIElement child, Thickness? margin=null) => new() { Child=child,Background=new SolidColorBrush(C("#72FFFFFF")),BorderBrush=new SolidColorBrush(C("#50FFFFFF")),BorderThickness=new(1),CornerRadius=new(16),Padding=new(18),Margin=margin??new(0,0,0,12),Effect=new System.Windows.Media.Effects.DropShadowEffect{BlurRadius=18,ShadowDepth=2,Opacity=.08} };
    TextBlock Text(string t,double size=14,Brush? color=null,FontWeight? weight=null)=>new(){Text=t,FontSize=size,Foreground=color??(Brush)FindResource("InkBrush"),FontWeight=weight??FontWeights.Normal,TextWrapping=TextWrapping.Wrap};
    void Nav_Click(object sender,RoutedEventArgs e) { page=(string)((Button)sender).Tag; Render(); }
    void Render() { switch(page){case "today":RenderToday();break;case "calendar":RenderCalendar();break;case "courses":RenderCourses();break;case "goals":RenderGoals();break;default:RenderStats();break;} }
    void Header(string title,string subtitle,bool add=true) { PageTitle.Text=title;PageSubtitle.Text=subtitle;AddButton.Visibility=add?Visibility.Visible:Visibility.Collapsed; }
    void RenderToday() {
        Header("今日待办",DateTime.Now.ToString("yyyy年M月d日 dddd")); var root=new StackPanel();
        var all=store.Data.Tasks.Where(x=>x.Start.Date==DateTime.Today).OrderBy(x=>x.Done).ThenBy(x=>x.Start).ToList();
        var summary=new Grid();summary.ColumnDefinitions.Add(new());summary.ColumnDefinitions.Add(new(){Width=new GridLength(190)}); var greet=new StackPanel();greet.Children.Add(Text(DateTime.Now.Hour<12?"早上好，今天也从容一点。":"把今天的事，轻轻放进日程。",19,null,FontWeights.SemiBold));greet.Children.Add(Text($"{all.Count(x=>!x.Done)} 件待完成 · {all.Count(x=>x.Done)} 件已完成",13,(Brush)FindResource("MutedBrush")));summary.Children.Add(greet);var progress=Text(all.Count==0?"今天尚无安排":$"完成度  {(int)(100.0*all.Count(x=>x.Done)/all.Count)}%",14,(Brush)FindResource("AccentBrush"),FontWeights.SemiBold);progress.HorizontalAlignment=HorizontalAlignment.Right;progress.VerticalAlignment=VerticalAlignment.Center;Grid.SetColumn(progress,1);summary.Children.Add(progress);root.Children.Add(Card(summary,new(0,0,0,18)));
        if(all.Count==0){var empty=new StackPanel{Margin=new(0,54,0,0),HorizontalAlignment=HorizontalAlignment.Center};empty.Children.Add(Text("○",50,(Brush)FindResource("AccentBrush")));empty.Children.Add(Text("这一天暂无事项",20,null,FontWeights.SemiBold));empty.Children.Add(Text("点击右上角，为今天安排一件小事",13,(Brush)FindResource("MutedBrush")));root.Children.Add(empty);} else foreach(var t in all) root.Children.Add(TaskCard(t));
        ContentHost.Children.Clear();ContentHost.Children.Add(root);
    }
    Border TaskCard(TodoItem t) { var grid=new Grid{Opacity=t.Done ? .55 : 1};grid.ColumnDefinitions.Add(new(){Width=new(6)});grid.ColumnDefinitions.Add(new());grid.ColumnDefinitions.Add(new(){Width=GridLength.Auto});var stripe=new Border{Background=new SolidColorBrush(priorityColors[(int)t.Priority]),CornerRadius=new(3)};grid.Children.Add(stripe);var body=new StackPanel{Margin=new(15,0,15,0)};body.Children.Add(Text($"{t.Start:HH:mm}  ·  {priorityNames[(int)t.Priority]}",12,new SolidColorBrush(priorityColors[(int)t.Priority]),FontWeights.SemiBold));body.Children.Add(Text(t.Title,17,null,FontWeights.SemiBold));if(t.DurationMinutes>0)body.Children.Add(Text($"预计 {t.DurationMinutes} 分钟 · 至 {Rules.End(t):HH:mm}",12,(Brush)FindResource("MutedBrush")));if(!string.IsNullOrWhiteSpace(t.Note))body.Children.Add(Text(t.Note,13,(Brush)FindResource("MutedBrush")));Grid.SetColumn(body,1);grid.Children.Add(body);var actions=new StackPanel{Orientation=Orientation.Horizontal,VerticalAlignment=VerticalAlignment.Center};var edit=new Button{Content="编辑",Tag=t,Margin=new(0,0,7,0)};edit.Click+=(s,e)=>EditTask((TodoItem)((Button)s).Tag);actions.Children.Add(edit);var done=new Button{Content=t.Done?"恢复":"✓ 完成",Tag=t};done.Click+=(s,e)=>{var x=(TodoItem)((Button)s).Tag;x.Done=!x.Done;x.CompletedAt=x.Done?DateTime.Now:null;store.Save();Render();};actions.Children.Add(done);Grid.SetColumn(actions,2);grid.Children.Add(actions);return Card(grid); }
    void Add_Click(object s,RoutedEventArgs e){if(page=="goals")EditGoal(null);else if(page=="courses")EditCourse(null);else EditTask(null);}
    void EditTask(TodoItem? original) { var isNew=original==null;var t=isNew?new TodoItem{Start=selected.Date==DateTime.Today?DateTime.Now.AddMinutes(30):selected.Date.AddHours(9)}:original!;var dialog=new Window{Title=isNew?"新建待办":"编辑待办",Owner=this,Width=520,Height=690,WindowStartupLocation=WindowStartupLocation.CenterOwner,Background=new SolidColorBrush(C("#F4F1E9"))};var panel=new StackPanel{Margin=new(28)};var title=new TextBox{Text=t.Title};var note=new TextBox{Text=t.Note,Height=75,AcceptsReturn=true};var date=new DatePicker{SelectedDate=t.Start.Date};var time=new TextBox{Text=t.Start.ToString("HH:mm")};var duration=new TextBox{Text=t.DurationMinutes==0?"":t.DurationMinutes.ToString()};var priority=new ComboBox{ItemsSource=priorityNames,SelectedIndex=(int)t.Priority,Padding=new(10,8,10,8)};var reminder=new ComboBox{ItemsSource=new[]{"不提醒","日程发生时","提前 10 分钟","提前 30 分钟","提前 1 小时","提前 1 天"},SelectedIndex=t.ReminderMinutes.Count==0?0:t.ReminderMinutes.Contains(0)?1:2,Padding=new(10,8,10,8)};void field(string label,FrameworkElement c){panel.Children.Add(Text(label,12,(Brush)FindResource("MutedBrush"),FontWeights.SemiBold));panel.Children.Add(c);panel.Children.Add(new Border{Height=12});}panel.Children.Add(Text(isNew?"安排一件小事":"编辑待办",25,null,FontWeights.SemiBold));panel.Children.Add(new Border{Height=18});field("事项名称 *",title);field("备注",note);var timeRow=new Grid();timeRow.ColumnDefinitions.Add(new());timeRow.ColumnDefinitions.Add(new(){Width=new GridLength(110)});timeRow.Children.Add(date);Grid.SetColumn(time,1);time.Margin=new(8,0,0,0);timeRow.Children.Add(time);field("预计开始时间",timeRow);field("轻重缓急",priority);field("预计持续时间（分钟）",duration);field("提醒",reminder);var buttons=new StackPanel{Orientation=Orientation.Horizontal,HorizontalAlignment=HorizontalAlignment.Right};if(!isNew){var del=new Button{Content="删除",Margin=new(0,0,8,0)};del.Click+=(s,e)=>{if(MessageBox.Show("删除这条事项？","轻待办",MessageBoxButton.YesNo)==MessageBoxResult.Yes){store.Data.Tasks.Remove(t);store.Save();dialog.DialogResult=true;}};buttons.Children.Add(del);}var save=new Button{Content="保存事项",Background=(Brush)FindResource("AccentBrush"),Foreground=Brushes.White};save.Click+=(s,e)=>{if(!TimeSpan.TryParse(time.Text,out var tm)||date.SelectedDate==null){MessageBox.Show("请输入有效日期和时间");return;}t.Title=title.Text.Trim();t.Note=note.Text.Trim();t.Start=date.SelectedDate.Value.Date+tm;t.Priority=(Priority)priority.SelectedIndex;if(!int.TryParse(duration.Text,out var d))d=0;t.DurationMinutes=d;t.ReminderMinutes=reminder.SelectedIndex switch{0=>[],1=>[0],2=>[10],3=>[30],4=>[60],_=>[1440]};var error=Rules.Validate(t,DateTime.Now,!isNew);if(error!=null){MessageBox.Show(error);return;}if(isNew)store.Data.Tasks.Add(t);store.Save();dialog.DialogResult=true;};buttons.Children.Add(save);panel.Children.Add(buttons);dialog.Content=new ScrollViewer{Content=panel};if(dialog.ShowDialog()==true)Render(); }
    void RenderCalendar() { Header("日历日程","按日期查看所有安排");var root=new Grid();root.ColumnDefinitions.Add(new(){Width=new GridLength(420)});root.ColumnDefinitions.Add(new());var cal=new Calendar{SelectionMode=CalendarSelectionMode.SingleDate,SelectedDate=selected,DisplayDate=selected,FontSize=15,Margin=new(0,0,18,0)};cal.SelectedDatesChanged+=(s,e)=>{selected=cal.SelectedDate??DateTime.Today;RenderCalendar();};root.Children.Add(Card(cal));var list=new StackPanel();list.Children.Add(Text(selected.ToString("M月d日 dddd"),21,null,FontWeights.SemiBold));list.Children.Add(new Border{Height=14});var tasks=store.Data.Tasks.Where(x=>x.Start.Date==selected.Date).OrderBy(x=>x.Done).ThenBy(x=>x.Start).ToList();if(tasks.Count==0)list.Children.Add(Text("这一天暂无事项",14,(Brush)FindResource("MutedBrush")));foreach(var t in tasks)list.Children.Add(TaskCard(t));Grid.SetColumn(list,1);root.Children.Add(list);ContentHost.Children.Clear();ContentHost.Children.Add(root); }
    void RenderGoals(){Header("目标","把长期目标拆成每天可以完成的小事");var root=new StackPanel();if(store.Data.Goals.Count==0)root.Children.Add(Card(Text("还没有目标。创建一个目标，轻待办会按天生成待办。",15,(Brush)FindResource("MutedBrush"))));foreach(var g in store.Data.Goals){var row=new Grid();row.ColumnDefinitions.Add(new());row.ColumnDefinitions.Add(new(){Width=GridLength.Auto});var body=new StackPanel();body.Children.Add(Text(g.Title,18,null,FontWeights.SemiBold));body.Children.Add(Text($"每日：{g.DailyTitle}  ·  {g.DailyTime:hh\\:mm}  ·  截止 {g.Deadline:M月d日}",13,(Brush)FindResource("MutedBrush")));row.Children.Add(body);var b=new Button{Content="编辑",Tag=g};b.Click+=(s,e)=>EditGoal((GoalItem)((Button)s).Tag);Grid.SetColumn(b,1);row.Children.Add(b);root.Children.Add(Card(row));}ContentHost.Children.Clear();ContentHost.Children.Add(root);}
    void EditGoal(GoalItem? goal){var isNew=goal==null;var g=goal??new();var title=PromptWindow.Show(this,isNew?"新建目标":"编辑目标",[("目标名称",g.Title),("每日待办标题",g.DailyTitle),("截止日期",g.Deadline.ToString("yyyy-MM-dd")),("每日时间",g.DailyTime.ToString("hh\\:mm"))]);if(title==null)return;if(!DateTime.TryParse(title[2],out var deadline)||!TimeSpan.TryParse(title[3],out var tm)){MessageBox.Show("日期或时间格式不正确");return;}g.Title=title[0];g.DailyTitle=title[1];g.Deadline=deadline.Date;g.DailyTime=tm;if(isNew)store.Data.Goals.Add(g);store.Save();GenerateGoalTasks();RenderGoals();}
    void GenerateGoalTasks(){var changed=false;foreach(var g in store.Data.Goals.Where(x=>x.AutoAdd)){for(var d=DateTime.Today;d<=g.Deadline.Date;d=d.AddDays(1)){if(!store.Data.Tasks.Any(x=>x.GoalId==g.Id&&x.Start.Date==d)){store.Data.Tasks.Add(new(){Title=string.IsNullOrWhiteSpace(g.DailyTitle)?g.Title:g.DailyTitle,Start=d+g.DailyTime,GoalId=g.Id});changed=true;}}}if(changed)store.Save();}
    void RenderCourses(){Header("课程表","2026—2027 学年第一学期 · 第 1–16 周");var root=new Grid();for(int i=0;i<8;i++)root.ColumnDefinitions.Add(new(){Width=i==0?new GridLength(65):new GridLength(1,GridUnitType.Star)});for(int i=0;i<14;i++)root.RowDefinitions.Add(new(){Height=i==0?new GridLength(40):new GridLength(62)});string[] days=["节次","周一","周二","周三","周四","周五","周六","周日"];for(int i=0;i<8;i++){var h=Text(days[i],13,(Brush)FindResource("MutedBrush"),FontWeights.SemiBold);h.HorizontalAlignment=HorizontalAlignment.Center;h.VerticalAlignment=VerticalAlignment.Center;Grid.SetColumn(h,i);root.Children.Add(h);}for(int p=1;p<=13;p++){var label=Text($"{p}\n{Rules.PeriodStarts[p-1]:hh\\:mm}",11,(Brush)FindResource("MutedBrush"));label.TextAlignment=TextAlignment.Center;label.VerticalAlignment=VerticalAlignment.Center;Grid.SetRow(label,p);root.Children.Add(label);}foreach(var c in store.Data.Courses){var card=new Border{Background=new SolidColorBrush(Color.FromArgb(190,priorityColors[c.ColorIndex%4].R,priorityColors[c.ColorIndex%4].G,priorityColors[c.ColorIndex%4].B)),CornerRadius=new(9),Margin=new(3),Padding=new(7),Tag=c};var tx=Text($"{c.Name}\n{c.Location}",12,Brushes.White,FontWeights.SemiBold);card.Child=tx;card.MouseLeftButtonUp+=(s,e)=>EditCourse((CourseItem)((Border)s).Tag);Grid.SetColumn(card,((int)c.Weekday+6)%7+1);Grid.SetRow(card,c.StartPeriod);Grid.SetRowSpan(card,Math.Max(1,c.EndPeriod-c.StartPeriod+1));root.Children.Add(card);}ContentHost.Children.Clear();ContentHost.Children.Add(Card(root));}
    void EditCourse(CourseItem? course){var isNew=course==null;var c=course??new();var v=PromptWindow.Show(this,isNew?"新建课程":"编辑课程",[("课程名称",c.Name),("上课地点",c.Location),("星期（1-7）",((int)c.Weekday==0?7:(int)c.Weekday).ToString()),("起始节次",c.StartPeriod.ToString()),("结束节次",c.EndPeriod.ToString()),("起始周",c.StartWeek.ToString()),("结束周",c.EndWeek.ToString())]);if(v==null)return;if(!int.TryParse(v[2],out var wd)||!int.TryParse(v[3],out var sp)||!int.TryParse(v[4],out var ep)||sp<1||ep>13||sp>ep){MessageBox.Show("请输入正确的星期和节次");return;}c.Name=v[0];c.Location=v[1];c.Weekday=wd==7?DayOfWeek.Sunday:(DayOfWeek)wd;c.StartPeriod=sp;c.EndPeriod=ep;int.TryParse(v[5],out var sw);int.TryParse(v[6],out var ew);c.StartWeek=sw;c.EndWeek=ew;if(isNew)store.Data.Courses.Add(c);store.Save();RenderCourses();}
    void RenderStats(){Header("统计","看看时间都去了哪里",false);var root=new StackPanel();var grid=new UniformGrid{Columns=3};var tasks=store.Data.Tasks;foreach(var x in new[]{("累计事项",tasks.Count.ToString()),("已完成",tasks.Count(t=>t.Done).ToString()),("完成率",tasks.Count==0?"0%":$"{tasks.Count(t=>t.Done)*100/tasks.Count}%")}){var p=new StackPanel();p.Children.Add(Text(x.Item2,34,(Brush)FindResource("AccentBrush"),FontWeights.SemiBold));p.Children.Add(Text(x.Item1,13,(Brush)FindResource("MutedBrush")));grid.Children.Add(Card(p,new(0,0,12,16)));}root.Children.Add(grid);root.Children.Add(Card(Text("近 7 天完成  "+string.Join("   ",Enumerable.Range(0,7).Select(i=>{var d=DateTime.Today.AddDays(i-6);return $"{d:ddd} {tasks.Count(t=>t.Done&&t.CompletedAt?.Date==d)}";})),15)));ContentHost.Children.Clear();ContentHost.Children.Add(root);}
}

public static class PromptWindow {
    public static string[]? Show(Window owner,string title,(string Label,string Value)[] fields){var w=new Window{Owner=owner,Title=title,Width=440,SizeToContent=SizeToContent.Height,WindowStartupLocation=WindowStartupLocation.CenterOwner,Background=new SolidColorBrush((Color)ColorConverter.ConvertFromString("#F4F1E9"))};var p=new StackPanel{Margin=new(24)};var inputs=new List<TextBox>();p.Children.Add(new TextBlock{Text=title,FontSize=23,FontWeight=FontWeights.SemiBold,Margin=new(0,0,0,16)});foreach(var f in fields){p.Children.Add(new TextBlock{Text=f.Label,Foreground=Brushes.DimGray,Margin=new(0,4,0,4)});var t=new TextBox{Text=f.Value,Padding=new(9),Margin=new(0,0,0,8)};inputs.Add(t);p.Children.Add(t);}var save=new Button{Content="保存",HorizontalAlignment=HorizontalAlignment.Right,Padding=new(22,9,22,9),Margin=new(0,8,0,0)};save.Click+=(s,e)=>w.DialogResult=true;p.Children.Add(save);w.Content=p;return w.ShowDialog()==true?inputs.Select(x=>x.Text.Trim()).ToArray():null;}
}
