using System.Net.Http;
using System.Text;
using System.Text.Json.Nodes;
using System.IO;

namespace LightTodo.Windows;
public sealed record SyncResult(bool Success,string Message,int Uploaded=0,int Downloaded=0,int Conflicts=0);
public sealed class WindowsSyncEngine {
    readonly LocalStore store;readonly WindowsAccountSession session=new();readonly HttpClient http=new();readonly string url=Environment.GetEnvironmentVariable("LIGHTTODO_SUPABASE_URL")?.TrimEnd('/')??"",key=Environment.GetEnvironmentVariable("LIGHTTODO_SUPABASE_ANON_KEY")??"";readonly string statePath=Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),"LightTodo","sync-state.txt");readonly string accountPath=Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),"LightTodo","sync-account.txt");
    public WindowsSyncEngine(LocalStore store){this.store=store;}
    public async Task<SyncResult> Sync(){try{if(!session.IsSignedIn)throw new InvalidOperationException("请先登录账户");if(url.Length==0||key.Length==0)throw new InvalidOperationException("尚未配置云端同步服务");if(File.Exists(accountPath)&&!File.ReadAllText(accountPath).Equals(session.Email,StringComparison.OrdinalIgnoreCase))throw new InvalidOperationException("本机数据已绑定其他账户，不能直接切换上传");var(down,conflicts)=await Pull();var up=await Upload();var(moreDown,moreConflicts)=await Pull();down+=moreDown;conflicts+=moreConflicts;store.Save(false);Directory.CreateDirectory(Path.GetDirectoryName(accountPath)!);File.WriteAllText(accountPath,session.Email);return new(true,$"同步完成：上传 {up}，下载 {down}"+(conflicts>0?$"，合并冲突 {conflicts}":""),up,down,conflicts);}catch(Exception e){return new(false,e.Message);}}
    async Task<int> Upload(){var count=0;foreach(var(table,items)in Collections())foreach(var entity in items.Where(x=>x.SyncDirty).ToList()){var create=entity.SyncVersion==0;var path=$"/rest/v1/{table}"+(create?"?select=*":$"?id=eq.{Uri.EscapeDataString(entity.SyncId)}&sync_version=eq.{entity.SyncVersion}&select=*");var rows=await Request(create?HttpMethod.Post:HttpMethod.Patch,path,ToCloud(entity));if(rows.Count==0)continue;entity.SyncVersion=rows[0]!["sync_version"]!.GetValue<long>();entity.SyncDirty=false;count++;}return count;}
    async Task<(int,int)> Pull(){long cursor=File.Exists(statePath)&&long.TryParse(File.ReadAllText(statePath),out var value)?value:0;int down=0,conflicts=0;while(true){var rows=await Request(HttpMethod.Post,"/rest/v1/rpc/pull_changes",new(){{"p_after",cursor},{"p_limit",500}});if(rows.Count==0)break;foreach(var row in rows){var change=row!.AsObject();var payload=change["payload"]!.AsObject();var type=change["entity_type"]!.GetValue<string>();var id=payload["id"]!.GetValue<string>();var local=Find(type,id);var version=payload["sync_version"]!.GetValue<long>();if(local!=null&&local.SyncDirty&&local.SyncVersion<version){local.SyncVersion=version;conflicts++;}else{Apply(type,payload,local);down++;}cursor=change["sync_seq"]!.GetValue<long>();}Directory.CreateDirectory(Path.GetDirectoryName(statePath)!);File.WriteAllText(statePath,cursor.ToString());if(rows.Count<500)break;}return(down,conflicts);}
    IEnumerable<(string,IEnumerable<SyncEntity>)> Collections(){yield return("tasks",store.Data.Tasks);yield return("goals",store.Data.Goals);yield return("courses",store.Data.Courses);}
    SyncEntity? Find(string type,string id)=>type switch{"task"=>store.Data.Tasks.FirstOrDefault(x=>x.SyncId==id),"goal"=>store.Data.Goals.FirstOrDefault(x=>x.SyncId==id),"course"=>store.Data.Courses.FirstOrDefault(x=>x.SyncId==id),_=>null};
    static long Ms(DateTime d)=>new DateTimeOffset(d.ToUniversalTime()).ToUnixTimeMilliseconds();static long? Ms(DateTime? d)=>d.HasValue?Ms(d.Value):null;static DateTime Date(long n)=>DateTimeOffset.FromUnixTimeMilliseconds(n).LocalDateTime;
    static JsonObject ToCloud(SyncEntity e){var o=new JsonObject{{"id",e.SyncId},{"created_at",Ms(e.CreatedAtUtc)},{"updated_at",Ms(e.UpdatedAtUtc)},{"deleted_at",Ms(e.DeletedAtUtc)}};if(e is TodoItem t){o["title"]=t.Title;o["note"]=t.Note;o["start_at"]=Ms(t.Start);o["duration_minutes"]=t.DurationMinutes;o["priority"]=(int)t.Priority;o["done"]=t.Done;o["completed_at"]=Ms(t.CompletedAt);o["reminder_minutes"]=new JsonArray(t.ReminderMinutes.Select(x=>(JsonNode?)x).ToArray());}else if(e is GoalItem g){o["title"]=g.Title;o["daily_title"]=g.DailyTitle;o["deadline"]=Ms(g.Deadline);o["daily_hour"]=g.DailyTime.Hours;o["daily_minute"]=g.DailyTime.Minutes;o["auto_add"]=g.AutoAdd;}else if(e is CourseItem c){o["name"]=c.Name;o["location"]=c.Location;o["teacher"]=c.Teacher;o["note"]="";o["weekday"]=(int)c.Weekday==0?7:(int)c.Weekday;o["start_period"]=c.StartPeriod;o["end_period"]=c.EndPeriod;o["start_week"]=c.StartWeek;o["end_week"]=c.EndWeek;o["color_index"]=c.ColorIndex;}return o;}
    void Apply(string type,JsonObject o,SyncEntity? existing){var entity=existing??(type switch{"task"=>new TodoItem(),"goal"=>new GoalItem(),"course"=>new CourseItem(),_=>throw new InvalidOperationException("未知同步数据")});entity.SyncId=Text(o,"id");entity.SyncVersion=o["sync_version"]!.GetValue<long>();entity.CreatedAtUtc=Date(o["created_at"]!.GetValue<long>()).ToUniversalTime();entity.UpdatedAtUtc=Date(o["updated_at"]!.GetValue<long>()).ToUniversalTime();entity.DeletedAtUtc=o["deleted_at"] is null?null:Date(o["deleted_at"]!.GetValue<long>()).ToUniversalTime();entity.SyncDirty=false;if(entity is TodoItem t){t.Title=Text(o,"title");t.Note=Text(o,"note");t.Start=Date(o["start_at"]!.GetValue<long>());t.DurationMinutes=o["duration_minutes"]!.GetValue<int>();t.Priority=(Priority)o["priority"]!.GetValue<int>();t.Done=o["done"]!.GetValue<bool>();t.CompletedAt=o["completed_at"] is null?null:Date(o["completed_at"]!.GetValue<long>());t.ReminderMinutes=new(o["reminder_minutes"]!.AsArray().Select(x=>x!.GetValue<int>()));if(existing==null)store.Data.Tasks.Add(t);}else if(entity is GoalItem g){g.Title=Text(o,"title");g.DailyTitle=Text(o,"daily_title");g.Deadline=Date(o["deadline"]!.GetValue<long>());g.DailyTime=new(o["daily_hour"]!.GetValue<int>(),o["daily_minute"]!.GetValue<int>(),0);g.AutoAdd=o["auto_add"]!.GetValue<bool>();if(existing==null)store.Data.Goals.Add(g);}else if(entity is CourseItem c){c.Name=Text(o,"name");c.Location=Text(o,"location");c.Teacher=Text(o,"teacher");var wd=o["weekday"]!.GetValue<int>();c.Weekday=wd==7?DayOfWeek.Sunday:(DayOfWeek)wd;c.StartPeriod=o["start_period"]!.GetValue<int>();c.EndPeriod=o["end_period"]!.GetValue<int>();c.StartWeek=o["start_week"]!.GetValue<int>();c.EndWeek=o["end_week"]!.GetValue<int>();c.ColorIndex=o["color_index"]!.GetValue<int>();if(existing==null)store.Data.Courses.Add(c);}}
    async Task<JsonArray> Request(HttpMethod method,string path,JsonObject body){using var request=new HttpRequestMessage(method,url+path){Content=new StringContent(body.ToJsonString(),Encoding.UTF8,"application/json")};request.Headers.Add("apikey",key);request.Headers.Authorization=new("Bearer",session.AccessToken);request.Headers.Add("Prefer","return=representation");using var response=await http.SendAsync(request);var text=await response.Content.ReadAsStringAsync();if(response.StatusCode==System.Net.HttpStatusCode.Unauthorized)throw new InvalidOperationException("登录状态已过期，请退出后重新登录");if(!response.IsSuccessStatusCode)throw new InvalidOperationException($"云端同步失败（{(int)response.StatusCode}）");return string.IsNullOrWhiteSpace(text)?new():JsonNode.Parse(text)!.AsArray();}static string Text(JsonObject o,string n)=>o[n]?.GetValue<string>()??"";
}
